finbourne/lusid-sdk-java

- sdk/src/test/java/com/finbourne/lusid/integration/ApiClientBuilder.java
- sdk/src/test/java/com/finbourne/lusid/integration/InstrumentLoader.java
- sdk/src/test/java/com/finbourne/lusid/integration/LusidApiTests.java
- sdk/src/test/java/com/finbourne/lusid/integration/TestConfigurationLoader.java
- sdk/src/test/java/com/finbourne/lusid/integration/TransactionsTests.java
Mainly need to review TransactionTests.java to check the TransactionRequest for totalConsideration, units and price for listed, otc and cash
> Loading transaction examples

- generate.sh
- sdk/lusid-sdk.iml
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Portfolios.java
> DEV-3039 Rename Trade to Transaction

- sdk/lusid-sdk.iml
- sdk/src/main/java/com/finbourne/lusid/utilities/ApiClientBuilder.java
- sdk/src/main/java/com/finbourne/lusid/utilities/ApiConfiguration.java
- sdk/src/main/java/com/finbourne/lusid/utilities/ApiConfigurationBuilder.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Bitemporal.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Holdings.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Portfolios.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Reconciliation.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Transactions.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/marketdata/Instruments.java
- sdk/src/test/java/com/finbourne/lusid/utilities/ApiExceptionTests.java
uses a proxy if optional proxy config is supplied
> Add proxy handling

- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Holdings.java
> TR-282: Fix API Funcs

- sdk/src/test/java/com/finbourne/lusid/utilities/ApiExceptionTests.java
> TR-282: Fix API func

- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Portfolios.java
Add paging support for "List portfolios for scope" function
> DEV-5935: Support paging for ListPortfoliosForScope

- sdk/src/test/java/com/finbourne/lusid/tutorials/marketdata/Instruments.java
> DEV-3742 Update test for paged instruments

- sdk/Dockerfile
Update base image for tests which is no longer working with jq
> DEV-7399 update mvn test image

- sdk/Dockerfile
> DEV-7399 update test Docker image

- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Holdings.java
> DEV-6524: Add new optional param for AdjustHolding

- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Bitemporal.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Portfolios.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/Transactions.java
> Update GetTransaction endpoint for pagination

- sdk/pom.xml
Fix incorrect values in the pom file
> CTECH-605 fix pom file

- sdk/lusid-sdk.iml
- sdk/pom.xml
Bumps [jackson-databind](https://github.com/FasterXML/jackson) from 2.12.1 to 2.12.6.1.
Fix package name
> CTECH-1039 fix jackson-databind dependabot alert

- sdk/pom.xml
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/BitemporalTest.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/HoldingsTest.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/PortfoliosTest.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/ReconciliationTest.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/TransactionsTest.java
- sdk/src/test/java/com/finbourne/lusid/utilities/TestDataUtilities.java
Update examples for BigDecimal
> CTECH-1018 Update for BigDecimal

- sdk/src/test/java/com/finbourne/lusid/tutorials/marketdata/InstrumentsTest.java
- sdk/src/test/unit/java/com/finbourne/lusid/utilities/InstrumentLoader.java
Update instruments used in examples
> CTECH-2828 update instruments in examples

- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/HoldingsTest.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/PortfoliosTest.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/ReconciliationTest.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/TransactionsTest.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/marketdata/InstrumentsTest.java
Increase default timeouts to 30s
> CTECH-2879 increase default timeouts to 30s

- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/PortfoliosTest.java
Reverts finbourne/lusid-sdk-java#102
> Revert "Plat 2838 - Add sortBy parameter for List Portfolios"

- sdk/src/main/java/com/finbourne/lusid/utilities/HttpClientFactory.java
> CTECH-3307: Resolve proxy IPs on each call

- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/BitemporalTest.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/PortfoliosTest.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/TransactionsTest.java
Update LTS sdk for breaking changes to LUSID API (removal of `start` parameter)
Code refactoring
> CTECH-3394 remove deprecated start parameter from apis

- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/BitemporalTest.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/PortfoliosTest.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/ReconciliationTest.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/ibor/TransactionsTest.java
- sdk/src/test/java/com/finbourne/lusid/tutorials/marketdata/InstrumentsTest.java
> CTECH-3394 fix missing parameters
